version: '3.5'

networks:
  laravel:

volumes:
  mysql-data:

# Laravel foundation config
x-laravel: &laravel-base
  volumes:
    - ./:/var/www
  env_file:
    - .env
    - .docker/laravel/docker.env
  networks:
    - laravel

services:
  # Webserver
  web:
    image: docker.pkg.github.com/gumbo-millennium/website/web
    build:
      context: .docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - 127.0.0.1:13370:13370
    networks:
      - laravel
    depends_on:
      - laravel
      - pma
      - mail

  # Application
  laravel:
    << : *laravel-base
    image: docker.pkg.github.com/gumbo-millennium/website/laravel
    build:
      context: .docker/laravel
      target: laravel

  # Application
  horizon:
    << : *laravel-base
    image: docker.pkg.github.com/gumbo-millennium/website/horizon
    build:
      context: .docker/laravel
      target: horizon

  # mysql database
  database:
    image: docker.pkg.github.com/gumbo-millennium/website/database
    build:
      context: .docker/database
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - 127.0.0.1:13376:3306
    networks:
      - laravel

  # Redis
  redis:
    image: redis:alpine
    networks:
      - laravel
    ports:
      - 127.0.0.1:13379:6379

  # PhpMyAdmin
  pma:
    image: docker.pkg.github.com/gumbo-millennium/website/phpmyadmin
    build:
      context: .docker/phpmyadmin
    networks:
      - laravel
    environment:
      PMA_HOST: database
      PMA_USER: phpmyadmin
      PMA_PASSWORD: phpmyadmin
    depends_on:
      - database

  # Mailhog (to test e-mail)
  mail:
    image: mailhog/mailhog:latest
    networks:
      - laravel
