version: '3.5'

networks:
  laravel:
    name: gumbo-website

volumes:
  mysql-data:

# Laravel foundation config
x-laravel: &laravel-base
  volumes:
    - ./:/var/www
  env_file:
    - .env
    - library/docker/laravel/docker.env
  networks:
    - laravel

services:
  # Webserver
  web:
    build:
      dockerfile: dockerfile
      context: library/docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - 127.13.37.1:80:80
    environment:
      VIRTUAL_HOST: gumbo.localhost
    networks:
      - laravel
    depends_on:
      - laravel
      - pma
      - mail

  # Application
  laravel:
    << : *laravel-base
    build:
      context: library/docker/laravel
      target: laravel

  # Application
  horizon:
    << : *laravel-base
    build:
      context: library/docker/laravel
      target: horizon

  # mysql database
  database:
    build:
      dockerfile: dockerfile
      context: library/docker/mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./library/docker/mysql/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: kiepo9Eeth0hoech5ooLa6ed8oaphaih
    ports:
      - 127.13.37.1:3306:3306
    networks:
      - laravel

  # Redis
  redis:
    image: redis:alpine
    networks:
      - laravel
    ports:
      - 127.13.37.1:6379:6379

  # PhpMyAdmin
  pma:
    build:
      dockerfile: dockerfile
      context: library/docker/phpmyadmin
    networks:
      laravel:
        aliases:
          - phpmyadmin.docker
    environment:
      PMA_HOST: database
      PMA_USER: phpmyadmin
      PMA_PASSWORD: 'etah2raith4Thee5eijeiYei(f3foh8I'
      VIRTUAL_HOST: pma.gumbo.localhost
    depends_on:
      - database

  # Mailhog (to test e-mail)
  mail:
    image: mailhog/mailhog:latest
    ports:
      - 127.13.37.1:8025:8025
    environment:
      VIRTUAL_HOST: mail.gumbo.localhost
      VIRTUAL_PORT: 8025
    networks:
      - laravel
