name: "Build Docker Compose images"
on:
  push:
    branches:
    - master
    - develop

jobs:
  laravel-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create empty env
        run: cp .env.example .env
      - name: Build images
        run: docker-compose build
      - name: Upload images
        run: docker-compose push
